/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template chooser, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author proxc
 */
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;

public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    Home home = new Home();
    Database db = new Database();
    String fileString = "";

    public Admin_Home() {
        initComponents();
        setLocationRelativeTo(null);
        addUserPanel.setVisible(false);
        addAdminPanel.setVisible(false);
        updateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addAdmin = new javax.swing.JLabel();
        attendanceLog = new javax.swing.JLabel();
        addUser = new javax.swing.JLabel();
        changePassword = new javax.swing.JLabel();
        removeUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        attendanceScrollView = new javax.swing.JScrollPane();
        attendanceLogDisplay = new javax.swing.JTable();
        addUserPanel = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        imageIcon = new javax.swing.JLabel();
        deleteImage = new javax.swing.JButton();
        chooseImage = new javax.swing.JButton();
        scannerDisp = new javax.swing.JLabel();
        scanInit = new javax.swing.JButton();
        deleteScan = new javax.swing.JButton();
        firstName = new javax.swing.JLabel();
        firstNameDisp = new javax.swing.JTextField();
        firstNameSep = new javax.swing.JSeparator();
        lastName = new javax.swing.JLabel();
        lastNameDisp = new javax.swing.JTextField();
        lastNameSep = new javax.swing.JSeparator();
        userID = new javax.swing.JLabel();
        userIdDisp = new javax.swing.JTextField();
        userIdSep = new javax.swing.JSeparator();
        designation = new javax.swing.JLabel();
        designationDisp = new javax.swing.JTextField();
        designationSep = new javax.swing.JSeparator();
        addImages = new javax.swing.JLabel();
        addFingerprint = new javax.swing.JLabel();
        errorDisp = new javax.swing.JTextField();
        removeUserPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addAdminPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/admin_white.png"))); // NOI18N
        jLabel16.setText(" Administrator Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel16)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        addAdmin.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        addAdmin.setForeground(new java.awt.Color(255, 255, 255));
        addAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_admin_settings_male_50px.png"))); // NOI18N
        addAdmin.setText("Add Admin");
        addAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminMouseClicked(evt);
            }
        });

        attendanceLog.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        attendanceLog.setForeground(new java.awt.Color(255, 255, 255));
        attendanceLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendanceLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/attendance_log_50px.png"))); // NOI18N
        attendanceLog.setText("Attendance Log");
        attendanceLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendanceLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceLogMouseClicked(evt);
            }
        });

        addUser.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        addUser.setForeground(new java.awt.Color(255, 255, 255));
        addUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/add_users.png"))); // NOI18N
        addUser.setText("Add Users");
        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserMouseClicked(evt);
            }
        });

        changePassword.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        changePassword.setForeground(new java.awt.Color(255, 255, 255));
        changePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/forgot_password.png"))); // NOI18N
        changePassword.setText("Change Password");
        changePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        removeUser.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        removeUser.setForeground(new java.awt.Color(255, 255, 255));
        removeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/remove_user_50px.png"))); // NOI18N
        removeUser.setText("Remove");
        removeUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeUser)
                    .addComponent(changePassword)
                    .addComponent(attendanceLog)
                    .addComponent(addUser)
                    .addComponent(addAdmin))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attendanceLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeUser)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        addUser.getAccessibleContext().setAccessibleName("Add User");
        changePassword.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 370));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendanceLogDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        attendanceLogDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        attendanceLogDisplay.setEnabled(false);
        attendanceLogDisplay.setFillsViewportHeight(true);
        attendanceLogDisplay.setShowGrid(false);
        attendanceScrollView.setViewportView(attendanceLogDisplay);

        jPanel3.add(attendanceScrollView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        addUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        addUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setBackground(new java.awt.Color(45, 118, 232));
        submit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(45, 118, 232));
        submit.setText("Submit");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        addUserPanel.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, 40));

        imageIcon.setBackground(new java.awt.Color(255, 255, 255));
        imageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_decision_100px.png"))); // NOI18N
        imageIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        imageIcon.setOpaque(true);
        addUserPanel.add(imageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 160, 120));

        deleteImage.setBackground(new java.awt.Color(255, 255, 255));
        deleteImage.setForeground(new java.awt.Color(45, 118, 232));
        deleteImage.setText("Delete");
        addUserPanel.add(deleteImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 70, -1));

        chooseImage.setBackground(new java.awt.Color(255, 255, 255));
        chooseImage.setForeground(new java.awt.Color(45, 118, 232));
        chooseImage.setText("Choose");
        chooseImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseImageMouseClicked(evt);
            }
        });
        addUserPanel.add(chooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 70, -1));

        scannerDisp.setBackground(new java.awt.Color(255, 255, 255));
        scannerDisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scannerDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_fingerprint_scan_100px.png"))); // NOI18N
        scannerDisp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        scannerDisp.setOpaque(true);
        addUserPanel.add(scannerDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 160, -1));

        scanInit.setBackground(new java.awt.Color(255, 255, 255));
        scanInit.setForeground(new java.awt.Color(45, 118, 232));
        scanInit.setText("Scan");
        scanInit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanInitMouseClicked(evt);
            }
        });
        addUserPanel.add(scanInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 70, -1));

        deleteScan.setBackground(new java.awt.Color(255, 255, 255));
        deleteScan.setForeground(new java.awt.Color(45, 118, 232));
        deleteScan.setText("Delete");
        addUserPanel.add(deleteScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 70, -1));

        firstName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstName.setForeground(new java.awt.Color(45, 118, 232));
        firstName.setText("First Name:");
        addUserPanel.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        firstNameDisp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        firstNameDisp.setForeground(new java.awt.Color(45, 118, 232));
        firstNameDisp.setBorder(null);
        firstNameDisp.setCaretColor(new java.awt.Color(45, 118, 232));
        firstNameDisp.setOpaque(false);
        addUserPanel.add(firstNameDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 140, 20));

        firstNameSep.setForeground(new java.awt.Color(45, 118, 232));
        addUserPanel.add(firstNameSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, 10));

        lastName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lastName.setForeground(new java.awt.Color(45, 118, 232));
        lastName.setText("Last Name:");
        addUserPanel.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        lastNameDisp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lastNameDisp.setForeground(new java.awt.Color(45, 118, 232));
        lastNameDisp.setBorder(null);
        lastNameDisp.setCaretColor(new java.awt.Color(45, 118, 232));
        lastNameDisp.setOpaque(false);
        addUserPanel.add(lastNameDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, 20));

        lastNameSep.setForeground(new java.awt.Color(45, 118, 232));
        addUserPanel.add(lastNameSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, 10));

        userID.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        userID.setForeground(new java.awt.Color(45, 118, 232));
        userID.setText("User ID:");
        addUserPanel.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 40));

        userIdDisp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        userIdDisp.setForeground(new java.awt.Color(45, 118, 232));
        userIdDisp.setBorder(null);
        userIdDisp.setCaretColor(new java.awt.Color(45, 118, 232));
        userIdDisp.setOpaque(false);
        addUserPanel.add(userIdDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, 20));

        userIdSep.setForeground(new java.awt.Color(45, 118, 232));
        addUserPanel.add(userIdSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, 10));

        designation.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        designation.setForeground(new java.awt.Color(45, 118, 232));
        designation.setText("Designation:");
        addUserPanel.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        designationDisp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        designationDisp.setForeground(new java.awt.Color(45, 118, 232));
        designationDisp.setBorder(null);
        designationDisp.setCaretColor(new java.awt.Color(45, 118, 232));
        designationDisp.setOpaque(false);
        addUserPanel.add(designationDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 20));

        designationSep.setForeground(new java.awt.Color(45, 118, 232));
        addUserPanel.add(designationSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, 10));

        addImages.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        addImages.setForeground(new java.awt.Color(45, 118, 232));
        addImages.setText("Add Image:");
        addUserPanel.add(addImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 20));

        addFingerprint.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        addFingerprint.setForeground(new java.awt.Color(45, 118, 232));
        addFingerprint.setText("Add Fingerprint:");
        addUserPanel.add(addFingerprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, 20));

        errorDisp.setEditable(false);
        errorDisp.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        errorDisp.setForeground(new java.awt.Color(45, 118, 232));
        errorDisp.setBorder(null);
        errorDisp.setOpaque(false);
        addUserPanel.add(errorDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 30));

        jPanel3.add(addUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        removeUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        removeUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        removeUserPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 40));

        jPanel3.add(removeUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        addAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        addAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 232));
        jLabel3.setText("Username:");
        addAdminPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jTextField1.setCaretColor(new java.awt.Color(45, 118, 232));
        addAdminPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("Password:");
        addAdminPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 30));

        jTextField2.setCaretColor(new java.awt.Color(45, 118, 232));
        addAdminPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 230, 30));

        jButton1.setBackground(new java.awt.Color(45, 118, 232));
        jButton1.setForeground(new java.awt.Color(45, 118, 232));
        jButton1.setText("jButton1");
        addAdminPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 40));

        jPanel3.add(addAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendanceLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLogMouseClicked
        // TODO add your handling code here:
        addUserPanel.setVisible(false);
        addAdminPanel.setVisible(false);
        attendanceScrollView.setVisible(true);
    }//GEN-LAST:event_attendanceLogMouseClicked

    private void chooseImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseImageMouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            FileFilter filter = new FileNameExtensionFilter("JPEG file, PNG", "jpg", "jpeg", "png", "gif");
            chooser.setFileFilter(filter);
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            fileString = f.getAbsolutePath();
            imageIcon.setIcon(ResizeImage(fileString)); //set image on label

        } catch (NullPointerException e) {
            System.out.println("Picture Not found \n" + e.getMessage());
        }

    }//GEN-LAST:event_chooseImageMouseClicked

    private void scanInitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanInitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scanInitMouseClicked

    private void addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserMouseClicked
        // TODO add your handling code here:
        attendanceScrollView.setVisible(false);
        addUserPanel.setVisible(true);
    }//GEN-LAST:event_addUserMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        insertUser();
    }//GEN-LAST:event_submitMouseClicked

    private void addAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminMouseClicked
        // TODO add your handling code here:
        attendanceScrollView.setVisible(false);
        addUserPanel.setVisible(false);
        addAdminPanel.setVisible(true);
    }//GEN-LAST:event_addAdminMouseClicked

    /**
     * @param ImagePath
     */
    //--------------------------------------------------------------------------------------
    //MY CODE
    private void resetValues() {
        userIdDisp.setText(null);
        firstNameDisp.setText(null);
        lastNameDisp.setText(null);
        designationDisp.setText(null);
        imageIcon.setIcon(ResizeImage("images/icons8_decision_100px"));
    }

    private String checkValues() {
        ArrayList<String> list = new ArrayList<>();
        list.add(userIdDisp.getText());
        list.add(firstNameDisp.getText());
        list.add(lastNameDisp.getText());
        list.add(designationDisp.getText());

        for (Iterator iterator = list.iterator(); iterator.hasNext();) {
            Object next = iterator.next();
            if (next.toString() == null || next.toString().trim().isEmpty()) {
                return "";
            }
        }
        return "Good";
    }

    private void insertUser() {

        if (checkValues().equals("Good") && !fileString.equals("")) {
            db.connect();

            String sql = "INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, DESIGNATION, IMAGE) VALUES (?,?,?,?,?)";

            try {
                db.ps = db.c.prepareStatement(sql);
                db.ps.setString(1, userIdDisp.getText());
                db.ps.setString(2, firstNameDisp.getText());
                db.ps.setString(3, lastNameDisp.getText());
                db.ps.setString(4, designationDisp.getText());
                db.ps.setBytes(5, readFile(fileString));

                db.ps.executeUpdate();

                db.ps.close();
                db.c.close();

                errorDisp.setForeground(new Color(45, 118, 232));
                errorDisp.setText("USER SUCCESSFULLY CREATED");

                resetValues();

                System.out.println("Successfully Added");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            errorDisp.setForeground(Color.RED);
            errorDisp.setText("*All Fields must be filled with a picture");
        }
    }

    private byte[] readFile(String file) {
        ByteArrayOutputStream bos = null;
        try {
            File f = new File(file);
            FileInputStream fis = new FileInputStream(f);
            byte[] buffer = new byte[1024];
            bos = new ByteArrayOutputStream();
            for (int len; (len = fis.read(buffer)) != -1;) {
                bos.write(buffer, 0, len);
            }
        } catch (FileNotFoundException e) {
            System.err.println(e.getMessage());
        } catch (IOException e2) {
            System.err.println(e2.getMessage());
        }
        return bos != null ? bos.toByteArray() : null;
    }

    private ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void updateTable() {
        db.connect();

        String sql = "SELECT USERID, FIRSTNAME, LASTNAME, TIME, DAY, MONTH "
                + "FROM USER INNER JOIN ATTENDANCELOG "
                + "ON FINGERPRINT = USERFINGER";
        try {
            db.ps = db.c.prepareStatement(sql);
            db.rs = db.ps.executeQuery();
            attendanceLogDisplay.setModel(DbUtils.resultSetToTableModel(db.rs));

            db.rs.close();
            db.ps.close();
            db.c.close();
            System.out.println("Databse Connection closed");
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAdmin;
    private javax.swing.JPanel addAdminPanel;
    private javax.swing.JLabel addFingerprint;
    private javax.swing.JLabel addImages;
    private javax.swing.JLabel addUser;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JLabel attendanceLog;
    private javax.swing.JTable attendanceLogDisplay;
    private javax.swing.JScrollPane attendanceScrollView;
    private javax.swing.JLabel changePassword;
    private javax.swing.JButton chooseImage;
    private javax.swing.JButton deleteImage;
    private javax.swing.JButton deleteScan;
    private javax.swing.JLabel designation;
    private javax.swing.JTextField designationDisp;
    private javax.swing.JSeparator designationSep;
    private javax.swing.JTextField errorDisp;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameDisp;
    private javax.swing.JSeparator firstNameSep;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameDisp;
    private javax.swing.JSeparator lastNameSep;
    private javax.swing.JLabel removeUser;
    private javax.swing.JPanel removeUserPanel;
    private javax.swing.JButton scanInit;
    private javax.swing.JLabel scannerDisp;
    private javax.swing.JButton submit;
    private javax.swing.JLabel userID;
    private javax.swing.JTextField userIdDisp;
    private javax.swing.JSeparator userIdSep;
    // End of variables declaration//GEN-END:variables
}
